DROP SEQUENCE SEQ_COUNTRY;
DROP SEQUENCE SEQ_CITY;
DROP SEQUENCE SEQ_PLAYER_POSITION;
DROP SEQUENCE SEQ_SEASON;

DROP TABLE T_SEASONS;
DROP TABLE T_PLAYER_POSITIONS;
DROP TABLE T_CITIES;
DROP TABLE T_COUNTRIES;

CREATE SEQUENCE SEQ_COUNTRY 
        MINVALUE 1 MAXVALUE 500 
        START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE SEQ_CITY 
        MINVALUE 1 MAXVALUE 100000 
        START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE SEQ_PLAYER_POSITION 
        MINVALUE 1 MAXVALUE 10 
        START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE  SEQ_SEASON 
        MINVALUE 1 MAXVALUE 1000 
        START WITH 1 INCREMENT BY 1 NOCACHE;

CREATE TABLE T_COUNTRIES(
  COUNTRY_ID NUMBER(3) DEFAULT SEQ_COUNTRY.NEXTVAL NOT NULL,
  COUNTRY_NAME VARCHAR2(75) NOT NULL,
  CONSTRAINT COUNTRY_ID_FK PRIMARY KEY (COUNTRY_ID),
  CONSTRAINT COUNTRY_NAME_UNIQUE UNIQUE (COUNTRY_NAME)
);

CREATE TABLE T_CITIES(
  CITY_ID NUMBER(9) DEFAULT SEQ_CITY.NEXTVAL NOT NULL,
  CITY_NAME VARCHAR2(75) NOT NULL,
  COUNTRY_ID NUMBER(3) NOT NULL,
  CONSTRAINT CITY_ID_FK PRIMARY KEY (CITY_ID),
  CONSTRAINT CITY_NAME_COUNTRY_ID_UNIQUE UNIQUE (CITY_NAME, COUNTRY_ID)
);

CREATE TABLE T_PLAYER_POSITIONS(
  PLAYER_POSITION_ID NUMBER(1) DEFAULT SEQ_PLAYER_POSITION.NEXTVAL NOT NULL,
  PLAYER_POSITION_NAME VARCHAR2(50) NOT NULL,
  CONSTRAINT PLAYER_POSITION_ID_FK PRIMARY KEY (PLAYER_POSITION_ID),
  CONSTRAINT PLAYER_POSITION_NAME_UNIQUE UNIQUE (PLAYER_POSITION_NAME)
);

CREATE TABLE T_SEASONS(
  SEASON_ID NUMBER(1) DEFAULT SEQ_SEASON.NEXTVAL NOT NULL,
  SEASON_NAME VARCHAR2(75) NOT NULL,
  SEASON_START NUMBER(4) NOT NULL,
  SEASON_END NUMBER(4) NOT NULL,
  CONSTRAINT SEASON_ID_FK PRIMARY KEY (SEASON_ID),
  CONSTRAINT SEASON_NAME_UNIQUE UNIQUE (SEASON_NAME)
);