DECLARE
  L_COUNTRY_FRANCE T_COUNTRIES%ROWTYPE;
  L_COUNTRY_GERMANY T_COUNTRIES%ROWTYPE;
  L_COUNTRY_ITALY T_COUNTRIES%ROWTYPE;
  L_COUNTRY_SPAIN T_COUNTRIES%ROWTYPE;
  L_COUNTRY_ENGLAND T_COUNTRIES%ROWTYPE;
  L_COUNTRY_RUSSIA T_COUNTRIES%ROWTYPE;
  
  L_CITY_RUSSIA_MOSCOW T_CITIES%ROWTYPE;
  L_CITY_ENGLAND_LONDON T_CITIES%ROWTYPE;
  L_CITY_SPAIN_BARCELONA T_CITIES%ROWTYPE;
BEGIN
  --SET DEFAULT VALUES
  L_COUNTRY_FRANCE.COUNTRY_NAME := 'FRANCE';
  L_COUNTRY_GERMANY.COUNTRY_NAME := 'GERMANY';
  L_COUNTRY_ITALY.COUNTRY_NAME := 'ITALY';
  L_COUNTRY_SPAIN.COUNTRY_NAME := 'SPAIN';
  L_COUNTRY_ENGLAND.COUNTRY_NAME := 'ENGLAND';
  L_COUNTRY_RUSSIA.COUNTRY_NAME := 'RUSSIA';
  
  L_CITY_RUSSIA_MOSCOW.CITY_NAME := 'MOSCOW';
  L_CITY_ENGLAND_LONDON.CITY_NAME := 'LONDON';
  L_CITY_SPAIN_BARCELONA.CITY_NAME := 'BARCELONA';

  --CLEAN UP
  PKG_CITY.DELETE_ALL_CITIES;
  PKG_COUNTRY.DELETE_ALL_COUNTRIES;
  
  --SET UP
  PKG_COUNTRY.INSERT_COUNTRY(L_COUNTRY_FRANCE.COUNTRY_NAME);
  PKG_COUNTRY.INSERT_COUNTRY(L_COUNTRY_GERMANY.COUNTRY_NAME);
  PKG_COUNTRY.INSERT_COUNTRY(L_COUNTRY_ITALY.COUNTRY_NAME);
  PKG_COUNTRY.INSERT_COUNTRY(L_COUNTRY_SPAIN.COUNTRY_NAME);
  PKG_COUNTRY.INSERT_COUNTRY(L_COUNTRY_ENGLAND.COUNTRY_NAME);
  PKG_COUNTRY.INSERT_COUNTRY(L_COUNTRY_RUSSIA.COUNTRY_NAME);
  
  L_COUNTRY_FRANCE.COUNTRY_ID := PKG_COUNTRY.GET_COUNTRY_BY_NAME(L_COUNTRY_FRANCE.COUNTRY_NAME);
  L_COUNTRY_GERMANY.COUNTRY_ID := PKG_COUNTRY.GET_COUNTRY_BY_NAME(L_COUNTRY_GERMANY.COUNTRY_NAME);
  L_COUNTRY_ITALY.COUNTRY_ID := PKG_COUNTRY.GET_COUNTRY_BY_NAME(L_COUNTRY_ITALY.COUNTRY_NAME);
  L_COUNTRY_SPAIN.COUNTRY_ID := PKG_COUNTRY.GET_COUNTRY_BY_NAME(L_COUNTRY_SPAIN.COUNTRY_NAME);
  L_COUNTRY_ENGLAND.COUNTRY_ID := PKG_COUNTRY.GET_COUNTRY_BY_NAME(L_COUNTRY_ENGLAND.COUNTRY_NAME);
  L_COUNTRY_RUSSIA.COUNTRY_ID := PKG_COUNTRY.GET_COUNTRY_BY_NAME(L_COUNTRY_RUSSIA.COUNTRY_NAME);
  
  PKG_CITY.INSERT_CITY(L_CITY_RUSSIA_MOSCOW.CITY_NAME, L_COUNTRY_RUSSIA.COUNTRY_ID);
  PKG_CITY.INSERT_CITY(L_CITY_ENGLAND_LONDON.CITY_NAME, L_COUNTRY_ENGLAND.COUNTRY_ID);
  PKG_CITY.INSERT_CITY(L_CITY_SPAIN_BARCELONA.CITY_NAME, L_COUNTRY_SPAIN.COUNTRY_ID);
END;