-----------------------COUNTRY
CREATE OR REPLACE PACKAGE PKG_COUNTRY
IS
  PROCEDURE INSERT_COUNTRY(COUNTRY_NAME_IN IN T_COUNTRIES.COUNTRY_NAME%TYPE);
  PROCEDURE DELETE_ALL_COUNTRIES;
  
  FUNCTION GET_COUNTRY_BY_NAME(COUNTRY_NAME_IN IN T_COUNTRIES.COUNTRY_NAME%TYPE)
  RETURN T_COUNTRIES.COUNTRY_ID%TYPE;
END PKG_COUNTRY;
/

CREATE OR REPLACE PACKAGE BODY PKG_COUNTRY
IS
  PROCEDURE INSERT_COUNTRY(COUNTRY_NAME_IN IN T_COUNTRIES.COUNTRY_NAME%TYPE)
  AS
  BEGIN
    INSERT INTO T_COUNTRIES(COUNTRY_NAME) VALUES(COUNTRY_NAME_IN);
    COMMIT;
  END INSERT_COUNTRY;
  
  PROCEDURE DELETE_ALL_COUNTRIES
  AS
  BEGIN
    DELETE FROM T_COUNTRIES;
    COMMIT;
  END DELETE_ALL_COUNTRIES;
  
  
  FUNCTION GET_COUNTRY_BY_NAME(COUNTRY_NAME_IN IN T_COUNTRIES.COUNTRY_NAME%TYPE)
  RETURN T_COUNTRIES.COUNTRY_ID%TYPE
  AS
    L_RETURN T_COUNTRIES.COUNTRY_ID%TYPE;
  BEGIN
    SELECT COUNTRY_ID INTO L_RETURN
    FROM T_COUNTRIES
    WHERE COUNTRY_NAME = COUNTRY_NAME_IN;
    RETURN L_RETURN;
  END GET_COUNTRY_BY_NAME;
  
END PKG_COUNTRY;
/

-----------------------CITY
CREATE OR REPLACE PACKAGE PKG_CITY
IS
  PROCEDURE INSERT_CITY(CITY_NAME_IN IN T_CITIES.CITY_NAME%TYPE,
                        COUNTRY_ID_IN IN T_CITIES.COUNTRY_ID%TYPE);
  PROCEDURE DELETE_ALL_CITIES;
  
  FUNCTION GET_COUNTRY_BY_NAME(CITY_NAME_IN IN T_CITIES.CITY_NAME%TYPE,
                               COUNTRY_ID_IN IN T_CITIES.COUNTRY_ID%TYPE)
  RETURN T_CITIES.CITY_ID%TYPE;
END PKG_CITY;
/

CREATE OR REPLACE PACKAGE BODY PKG_CITY
IS
  PROCEDURE INSERT_CITY(CITY_NAME_IN IN T_CITIES.CITY_NAME%TYPE,
                        COUNTRY_ID_IN IN T_CITIES.COUNTRY_ID%TYPE)
  AS
  BEGIN
    INSERT INTO T_CITIES(CITY_NAME, COUNTRY_ID) VALUES(CITY_NAME_IN, COUNTRY_ID_IN);
    COMMIT;
  END INSERT_CITY;
  
  PROCEDURE DELETE_ALL_CITIES
  AS
  BEGIN
    DELETE FROM T_CITIES;
  END DELETE_ALL_CITIES;
  
  FUNCTION GET_COUNTRY_BY_NAME(CITY_NAME_IN IN T_CITIES.CITY_NAME%TYPE,
                               COUNTRY_ID_IN IN T_CITIES.COUNTRY_ID%TYPE)
  RETURN T_CITIES.CITY_ID%TYPE
  AS
    L_RETURN T_CITIES.CITY_ID%TYPE;
  BEGIN
    SELECT CITY_ID INTO L_RETURN
    FROM T_CITIES
    WHERE CITY_NAME = CITY_NAME_IN AND COUNTRY_ID = COUNTRY_ID_IN;
    RETURN L_RETURN;
  END GET_COUNTRY_BY_NAME;
  
END PKG_CITY;
/
SHOW ERRORS;