CREATE OR REPLACE SYNONYM T_LANGUAGES FOR USER_WORD_DB.T_LANGUAGES;
CREATE OR REPLACE SYNONYM T_PART_OF_SPEECHES FOR USER_WORD_DB.T_PART_OF_SPEECHES;
CREATE OR REPLACE SYNONYM T_WORDS FOR USER_WORD_DB.T_WORDS;
CREATE OR REPLACE SYNONYM T_WORDS_PART_OF_SPEECHES FOR USER_WORD_DB.T_WORDS_PART_OF_SPEECHES;
CREATE OR REPLACE SYNONYM T_TRANSLATES FOR USER_WORD_DB.T_TRANSLATES;