SET SERVEROUTPUT ON;
begin
  update T_ACCOUNTS set COUNT_DAY_NEED_CHANGE_PASS = 2 where ACCOUNT_USER_ID = 1;
  update T_PASSWORD_HISTORY set AC_PAS_CHANGE_DATE_TIME = AC_PAS_CHANGE_DATE_TIME - 3 where ACCOUNT_USER_ID = 1;
  commit;
  PKG_USER_MANAGEMENT.LOCKED_USER_EXPIRED_ACCOUNTS;
end;