--PROMPT--------------CREATE SEQUENCES--------------;
--CREATE SEQUENCES
CREATE SEQUENCE SEQ_LANGUAGES MINVALUE 1 MAXVALUE 999999999999999 START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE SEQ_PART_OF_SPEECHES MINVALUE 1 MAXVALUE 999999999999999 START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE SEQ_WORDS MINVALUE 1 MAXVALUE 999999999999999 START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE SEQ_TRANSLATES MINVALUE 1 MAXVALUE 999999999999999 START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE SEQ_WORDS_PART_OF_SPEECHE MINVALUE 1 MAXVALUE 999999999999999 START WITH 1 INCREMENT BY 1 NOCACHE;

--PROMPT--------------CREATE TABLES--------------;
--CREATE TABLES
CREATE TABLE T_C_OPERATIONS(
	OPERATION_ID NUMBER(1,0) NOT NULL,
	OPERATION_NAME VARCHAR2(50 BYTE) NOT NULL,
	CONSTRAINT OPERATION_ID_PK PRIMARY KEY (OPERATION_ID),
	CONSTRAINT OPERATION_NAME_UNIQUE UNIQUE (OPERATION_NAME)
);

CREATE TABLE T_LANGUAGES
(
	LANGUAGE_ID   NUMBER(10,0) DEFAULT SEQ_LANGUAGES.NEXTVAL NOT NULL ,
	LANGUAGE_NAME VARCHAR2(50 BYTE) NOT NULL ,
	CONSTRAINT LANGUAGE_ID_PK PRIMARY KEY (LANGUAGE_ID)
);

CREATE TABLE T_PART_OF_SPEECHES
(
	PART_OF_SPEECH_ID NUMBER(10,0) DEFAULT SEQ_PART_OF_SPEECHES.NEXTVAL NOT NULL ,
	PART_OF_SPEECH    VARCHAR2(50 BYTE) NOT NULL ,
	CONSTRAINT PART_OF_SPEECH_ID_PK PRIMARY KEY (PART_OF_SPEECH_ID)
);

CREATE TABLE T_WORDS
(
	WORD_ID           NUMBER(10,0) DEFAULT SEQ_WORDS.NEXTVAL NOT NULL ,
	WORD              VARCHAR2(50 BYTE) NOT NULL ,
	LANGUAGE_ID       NUMBER(10,0) NOT NULL ,
	CONSTRAINT WORD_ID_PK PRIMARY KEY (WORD_ID),
	CONSTRAINT T_W_LANGUAGE_ID_FK FOREIGN KEY (LANGUAGE_ID) REFERENCES T_LANGUAGES (LANGUAGE_ID)
);

CREATE TABLE T_WORDS_PART_OF_SPEECHES(
	PART_OF_SPEECH_WORD_ID NUMBER(10,0) DEFAULT SEQ_WORDS_PART_OF_SPEECHE.NEXTVAL NOT NULL ,
	WORD_ID           NUMBER(10,0) NOT NULL ,
	PART_OF_SPEECH_ID NUMBER(10,0) NOT NULL ,
	CONSTRAINT PART_OF_SPEECH_WORD_ID_PK PRIMARY KEY (PART_OF_SPEECH_WORD_ID),
	CONSTRAINT T_WPOS_WORD_ID_FK FOREIGN KEY (WORD_ID) REFERENCES T_WORDS (WORD_ID),
	CONSTRAINT T_WPOS_PART_OF_SPEECH_ID_FK FOREIGN KEY (PART_OF_SPEECH_ID) REFERENCES T_PART_OF_SPEECHES (PART_OF_SPEECH_ID)
);

CREATE TABLE T_TRANSLATES
(
	TRANSLATE_ID NUMBER(10,0) DEFAULT SEQ_TRANSLATES.NEXTVAL NOT NULL ,
	PART_OF_SPEECH_WORD_ID_F    NUMBER(10,0) NOT NULL ,
	PART_OF_SPEECH_WORD_ID_S    NUMBER(10,0) NOT NULL ,
	CONSTRAINT TRANSLATE_ID_PK PRIMARY KEY (TRANSLATE_ID)
);

--ALTER TABLES
ALTER TABLE T_TRANSLATES ADD CONSTRAINT T_T_PART_OF_SH_WORD_ID_F_FK FOREIGN KEY (PART_OF_SPEECH_WORD_ID_F) REFERENCES T_WORDS_PART_OF_SPEECHES (PART_OF_SPEECH_WORD_ID) ;
ALTER TABLE T_TRANSLATES ADD CONSTRAINT T_T_PART_OF_SH_WORD_ID_S_FK FOREIGN KEY (PART_OF_SPEECH_WORD_ID_S) REFERENCES T_WORDS_PART_OF_SPEECHES (PART_OF_SPEECH_WORD_ID) ;

--PROMPT---------------CREATE AUDITED TABLES--------------;
CREATE TABLE AUDIT_LANGUAGES
(
	LANGUAGE_ID   NUMBER(10,0) NOT NULL ,
	CREATED_DATE_TIME TIMESTAMP NULL ,
	UPDATED_DATE_TIME TIMESTAMP NOT NULL ,
	OPERATION_ID NUMBER(1,0) NOT NULL,
	CONSTRAINT A_L_LANGUAGE_ID_FK FOREIGN KEY (LANGUAGE_ID) REFERENCES T_LANGUAGES (LANGUAGE_ID),
	CONSTRAINT A_L_OPERATION_ID_FK FOREIGN KEY (OPERATION_ID) REFERENCES T_C_OPERATIONS (OPERATION_ID)
);

CREATE TABLE AUDIT_PART_OF_SPEECHES
(
	PART_OF_SPEECH_ID   NUMBER(10,0) NOT NULL ,
	CREATED_DATE_TIME TIMESTAMP NULL ,
	UPDATED_DATE_TIME TIMESTAMP NOT NULL ,
	OPERATION_ID NUMBER(1,0) NOT NULL,
	CONSTRAINT A_P_PART_OF_SPEECH_ID_FK FOREIGN KEY (PART_OF_SPEECH_ID) REFERENCES T_PART_OF_SPEECHES (PART_OF_SPEECH_ID),
	CONSTRAINT A_P_OPERATION_ID_FK FOREIGN KEY (OPERATION_ID) REFERENCES T_C_OPERATIONS (OPERATION_ID)
);

CREATE TABLE AUDIT_WORDS
(
	WORD_ID   NUMBER(10,0) NOT NULL ,
	CREATED_DATE_TIME TIMESTAMP NULL ,
	UPDATED_DATE_TIME TIMESTAMP NOT NULL ,
	OPERATION_ID NUMBER(1,0) NOT NULL,
	CONSTRAINT A_W_WORD_ID_FK FOREIGN KEY (WORD_ID) REFERENCES T_WORDS (WORD_ID),
	CONSTRAINT A_W_OPERATION_ID_FK FOREIGN KEY (OPERATION_ID) REFERENCES T_C_OPERATIONS (OPERATION_ID)
);

CREATE TABLE AUDIT_TRANSLATES
(
	TRANSLATE_ID   NUMBER(10,0) NOT NULL ,
	CREATED_DATE_TIME TIMESTAMP NULL ,
	UPDATED_DATE_TIME TIMESTAMP NOT NULL ,
	OPERATION_ID NUMBER(1,0) NOT NULL,
	CONSTRAINT A_T_TRANSLATE_ID_FK FOREIGN KEY (TRANSLATE_ID) REFERENCES T_TRANSLATES (TRANSLATE_ID),
	CONSTRAINT A_T_OPERATION_ID_FK FOREIGN KEY (OPERATION_ID) REFERENCES T_C_OPERATIONS (OPERATION_ID)
);

--PROMPT---------------CREATE VIEWS--------------;
--CREATE VIEWIES
CREATE OR REPLACE VIEW V_LANGUAGES AS
	SELECT *
	FROM T_LANGUAGES;

CREATE OR REPLACE VIEW V_PART_OF_SPEECHES AS
	SELECT *
	FROM T_PART_OF_SPEECHES;

CREATE OR REPLACE VIEW V_WORDS AS
	SELECT W.*, L.LANGUAGE_NAME
	FROM T_WORDS W INNER JOIN T_LANGUAGES L ON L.LANGUAGE_ID = W.LANGUAGE_ID;

CREATE OR REPLACE VIEW V_WORDS_PART_OF_SPEECHES AS
	SELECT WPOS.*, W.WORD, W.LANGUAGE_NAME, POS.PART_OF_SPEECH
	FROM T_WORDS_PART_OF_SPEECHES WPOS INNER JOIN V_WORDS W ON WPOS.WORD_ID = W.WORD_ID
	INNER JOIN T_PART_OF_SPEECHES POS ON POS.PART_OF_SPEECH_ID = WPOS.PART_OF_SPEECH_ID;

CREATE OR REPLACE VIEW V_TRANSLATES AS
	SELECT T.TRANSLATE_ID, T.PART_OF_SPEECH_WORD_ID_F,
		FIRST_WORD.WORD_ID AS FW_WORD_ID, FIRST_WORD.PART_OF_SPEECH_ID AS FW_PART_OF_SPEECH_ID,
    FIRST_WORD.WORD AS FW_WORD, FIRST_WORD.LANGUAGE_NAME AS FW_LANGUAGE_NAME,
    FIRST_WORD.PART_OF_SPEECH AS FW_PART_OF_SPEECH,
    T.PART_OF_SPEECH_WORD_ID_S,
		SECOND_WORD.WORD_ID AS SW_WORD_ID, SECOND_WORD.PART_OF_SPEECH_ID AS SW_PART_OF_SPEECH_ID,
    SECOND_WORD.WORD AS SW_WORD, SECOND_WORD.LANGUAGE_NAME AS SW_LANGUAGE_NAME,
    SECOND_WORD.PART_OF_SPEECH AS SW_PART_OF_SPEECH
	FROM T_TRANSLATES T,
		(SELECT * FROM V_WORDS_PART_OF_SPEECHES VWPOS) FIRST_WORD,
		(SELECT * FROM V_WORDS_PART_OF_SPEECHES VWPOS) SECOND_WORD
	WHERE FIRST_WORD.PART_OF_SPEECH_WORD_ID = T.PART_OF_SPEECH_WORD_ID_F AND SECOND_WORD.PART_OF_SPEECH_WORD_ID = T.PART_OF_SPEECH_WORD_ID_S;

CREATE OR REPLACE VIEW V_S_TRANSLATES AS
  SELECT T.TRANSLATE_ID, T.FW_WORD, T.SW_WORD
  FROM V_TRANSLATES T;

--PROMPT---------------CREATE AUDITED VIEWS--------------;
CREATE OR REPLACE VIEW V_AUDIT_LANGUAGES AS
	SELECT l.LANGUAGE_NAME, al.*
	FROM T_LANGUAGES l INNER JOIN AUDIT_LANGUAGES al ON l.LANGUAGE_ID = al.LANGUAGE_ID;

CREATE OR REPLACE VIEW V_AUDIT_PART_OF_SPEECHES AS
	SELECT pos.PART_OF_SPEECH, apos.*
	FROM T_PART_OF_SPEECHES pos INNER JOIN AUDIT_PART_OF_SPEECHES apos ON pos.PART_OF_SPEECH_ID = apos.PART_OF_SPEECH_ID ;

CREATE OR REPLACE VIEW V_AUDIT_WORDS AS
	SELECT W.WORD, AW.*
	FROM T_WORDS W INNER JOIN AUDIT_WORDS AW ON W.WORD_ID = AW.WORD_ID;
/*
/
SHOW ERRORS;*/
