--PROMPT--------------CREATE TABLES--------------;
--CREATE TABLES
CREATE TABLE T_C_OPERATIONS(
	OPERATION_ID NUMBER(1,0) NOT NULL,
	OPERATION_NAME VARCHAR2(50 BYTE) NOT NULL,
	CONSTRAINT OPERATION_ID_PK PRIMARY KEY (OPERATION_ID),
	CONSTRAINT OPERATION_NAME_UNIQUE UNIQUE (OPERATION_NAME)
);
COMMENT ON TABLE T_C_OPERATIONS IS 'This table store operations name for audit, which use on triggers';
COMMENT ON COLUMN T_C_OPERATIONS.OPERATION_ID IS 'This column store operation id';
COMMENT ON COLUMN T_C_OPERATIONS.OPERATION_NAME IS 'This column store operation name';

CREATE TABLE T_LANGUAGES
(
	LANGUAGE_ID   NUMBER(10,0) DEFAULT SEQ_LANGUAGES.NEXTVAL NOT NULL ,
	LANGUAGE_NAME VARCHAR2(50 BYTE) NOT NULL ,
	CONSTRAINT LANGUAGE_ID_PK PRIMARY KEY (LANGUAGE_ID)
);
COMMENT ON TABLE T_LANGUAGES IS 'This table store languages';
COMMENT ON COLUMN T_LANGUAGES.LANGUAGE_ID IS 'This column store language id';
COMMENT ON COLUMN T_LANGUAGES.LANGUAGE_NAME IS 'This column store language name';

CREATE TABLE T_PART_OF_SPEECHES
(
	PART_OF_SPEECH_ID NUMBER(10,0) DEFAULT SEQ_PART_OF_SPEECHES.NEXTVAL NOT NULL ,
	PART_OF_SPEECH    VARCHAR2(50 BYTE) NOT NULL ,
	CONSTRAINT PART_OF_SPEECH_ID_PK PRIMARY KEY (PART_OF_SPEECH_ID)
);
COMMENT ON TABLE T_PART_OF_SPEECHES IS 'This table store part of speeches';
COMMENT ON COLUMN T_PART_OF_SPEECHES.PART_OF_SPEECH_ID IS 'This column store part of speech id';
COMMENT ON COLUMN T_PART_OF_SPEECHES.PART_OF_SPEECH IS 'This column store part of speech';

CREATE TABLE T_WORDS
(
	WORD_ID           NUMBER(10,0) DEFAULT SEQ_WORDS.NEXTVAL NOT NULL ,
	WORD              VARCHAR2(50 BYTE) NOT NULL ,
	LANGUAGE_ID       NUMBER(10,0) NOT NULL ,
	CONSTRAINT WORD_ID_PK PRIMARY KEY (WORD_ID),
	CONSTRAINT T_W_LANGUAGE_ID_FK FOREIGN KEY (LANGUAGE_ID) REFERENCES T_LANGUAGES (LANGUAGE_ID)
);
COMMENT ON TABLE T_WORDS IS 'This table store words';
COMMENT ON COLUMN T_WORDS.WORD_ID IS 'This column store word id';
COMMENT ON COLUMN T_WORDS.WORD IS 'This column store word';
COMMENT ON COLUMN T_WORDS.LANGUAGE_ID IS 'This column store language id';

CREATE TABLE T_WORDS_PART_OF_SPEECHES(
	PART_OF_SPEECH_WORD_ID NUMBER(10,0) DEFAULT SEQ_WORDS_PART_OF_SPEECHE.NEXTVAL NOT NULL ,
	WORD_ID           NUMBER(10,0) NOT NULL ,
	PART_OF_SPEECH_ID NUMBER(10,0) NOT NULL ,
	CONSTRAINT PART_OF_SPEECH_WORD_ID_PK PRIMARY KEY (PART_OF_SPEECH_WORD_ID),
	CONSTRAINT T_WPOS_WORD_ID_FK FOREIGN KEY (WORD_ID) REFERENCES T_WORDS (WORD_ID),
	CONSTRAINT T_WPOS_PART_OF_SPEECH_ID_FK FOREIGN KEY (PART_OF_SPEECH_ID) REFERENCES T_PART_OF_SPEECHES (PART_OF_SPEECH_ID)
);
COMMENT ON TABLE T_WORDS_PART_OF_SPEECHES IS 'This table store references word with part of speech';
COMMENT ON COLUMN T_WORDS_PART_OF_SPEECHES.PART_OF_SPEECH_WORD_ID IS 'This column store part of speech and word id';
COMMENT ON COLUMN T_WORDS_PART_OF_SPEECHES.WORD_ID IS 'This column store word id';
COMMENT ON COLUMN T_WORDS_PART_OF_SPEECHES.PART_OF_SPEECH_ID IS 'This column store part of speech id';

CREATE TABLE T_TRANSLATES
(
	TRANSLATE_ID NUMBER(10,0) DEFAULT SEQ_TRANSLATES.NEXTVAL NOT NULL ,
	PART_OF_SPEECH_WORD_ID_F    NUMBER(10,0) NOT NULL ,
	PART_OF_SPEECH_WORD_ID_S    NUMBER(10,0) NOT NULL ,
	CONSTRAINT TRANSLATE_ID_PK PRIMARY KEY (TRANSLATE_ID)
);
COMMENT ON TABLE T_TRANSLATES IS 'This table store translates';
COMMENT ON COLUMN T_TRANSLATES.TRANSLATE_ID IS 'This column store translate id';
COMMENT ON COLUMN T_TRANSLATES.PART_OF_SPEECH_WORD_ID_F IS 'This column store word id first';
COMMENT ON COLUMN T_TRANSLATES.PART_OF_SPEECH_WORD_ID_S IS 'This column store word id second';

--ALTER TABLES
ALTER TABLE T_TRANSLATES ADD CONSTRAINT T_T_PART_OF_SH_WORD_ID_F_FK FOREIGN KEY (PART_OF_SPEECH_WORD_ID_F) REFERENCES T_WORDS_PART_OF_SPEECHES (PART_OF_SPEECH_WORD_ID) ;
ALTER TABLE T_TRANSLATES ADD CONSTRAINT T_T_PART_OF_SH_WORD_ID_S_FK FOREIGN KEY (PART_OF_SPEECH_WORD_ID_S) REFERENCES T_WORDS_PART_OF_SPEECHES (PART_OF_SPEECH_WORD_ID) ;
