--PROMPT--------------CREATE TABLES--------------;
--CREATE TABLES
CREATE TABLE T_C_OPERATIONS(
	OPERATION_ID NUMBER(1,0) NOT NULL,
	OPERATION_NAME VARCHAR2(50 BYTE) NOT NULL,
	CONSTRAINT OPERATION_ID_PK PRIMARY KEY (OPERATION_ID),
	CONSTRAINT OPERATION_NAME_UNIQUE UNIQUE (OPERATION_NAME)
);

CREATE TABLE T_LANGUAGES
(
	LANGUAGE_ID   NUMBER(10,0) DEFAULT SEQ_LANGUAGES.NEXTVAL NOT NULL ,
	LANGUAGE_NAME VARCHAR2(50 BYTE) NOT NULL ,
	CONSTRAINT LANGUAGE_ID_PK PRIMARY KEY (LANGUAGE_ID)
);

CREATE TABLE T_PART_OF_SPEECHES
(
	PART_OF_SPEECH_ID NUMBER(10,0) DEFAULT SEQ_PART_OF_SPEECHES.NEXTVAL NOT NULL ,
	PART_OF_SPEECH    VARCHAR2(50 BYTE) NOT NULL ,
	CONSTRAINT PART_OF_SPEECH_ID_PK PRIMARY KEY (PART_OF_SPEECH_ID)
);

CREATE TABLE T_WORDS
(
	WORD_ID           NUMBER(10,0) DEFAULT SEQ_WORDS.NEXTVAL NOT NULL ,
	WORD              VARCHAR2(50 BYTE) NOT NULL ,
	LANGUAGE_ID       NUMBER(10,0) NOT NULL ,
	CONSTRAINT WORD_ID_PK PRIMARY KEY (WORD_ID),
	CONSTRAINT T_W_LANGUAGE_ID_FK FOREIGN KEY (LANGUAGE_ID) REFERENCES T_LANGUAGES (LANGUAGE_ID)
);

CREATE TABLE T_WORDS_PART_OF_SPEECHES(
	PART_OF_SPEECH_WORD_ID NUMBER(10,0) DEFAULT SEQ_WORDS_PART_OF_SPEECHE.NEXTVAL NOT NULL ,
	WORD_ID           NUMBER(10,0) NOT NULL ,
	PART_OF_SPEECH_ID NUMBER(10,0) NOT NULL ,
	CONSTRAINT PART_OF_SPEECH_WORD_ID_PK PRIMARY KEY (PART_OF_SPEECH_WORD_ID),
	CONSTRAINT T_WPOS_WORD_ID_FK FOREIGN KEY (WORD_ID) REFERENCES T_WORDS (WORD_ID),
	CONSTRAINT T_WPOS_PART_OF_SPEECH_ID_FK FOREIGN KEY (PART_OF_SPEECH_ID) REFERENCES T_PART_OF_SPEECHES (PART_OF_SPEECH_ID)
);

CREATE TABLE T_TRANSLATES
(
	TRANSLATE_ID NUMBER(10,0) DEFAULT SEQ_TRANSLATES.NEXTVAL NOT NULL ,
	PART_OF_SPEECH_WORD_ID_F    NUMBER(10,0) NOT NULL ,
	PART_OF_SPEECH_WORD_ID_S    NUMBER(10,0) NOT NULL ,
	CONSTRAINT TRANSLATE_ID_PK PRIMARY KEY (TRANSLATE_ID)
);

--ALTER TABLES
ALTER TABLE T_TRANSLATES ADD CONSTRAINT T_T_PART_OF_SH_WORD_ID_F_FK FOREIGN KEY (PART_OF_SPEECH_WORD_ID_F) REFERENCES T_WORDS_PART_OF_SPEECHES (PART_OF_SPEECH_WORD_ID) ;
ALTER TABLE T_TRANSLATES ADD CONSTRAINT T_T_PART_OF_SH_WORD_ID_S_FK FOREIGN KEY (PART_OF_SPEECH_WORD_ID_S) REFERENCES T_WORDS_PART_OF_SPEECHES (PART_OF_SPEECH_WORD_ID) ;
