--PROMPT---------------CREATE AUDITED TABLES--------------;
CREATE TABLE AUDIT_LANGUAGES
(
	LANGUAGE_ID   NUMBER(10,0) NOT NULL ,
	CREATED_DATE_TIME TIMESTAMP NULL ,
	UPDATED_DATE_TIME TIMESTAMP NOT NULL ,
	OPERATION_ID NUMBER(1,0) NOT NULL,
	CONSTRAINT A_L_LANGUAGE_ID_FK FOREIGN KEY (LANGUAGE_ID) REFERENCES T_LANGUAGES (LANGUAGE_ID),
	CONSTRAINT A_L_OPERATION_ID_FK FOREIGN KEY (OPERATION_ID) REFERENCES T_C_OPERATIONS (OPERATION_ID)
);
COMMENT ON TABLE AUDIT_LANGUAGES IS 'This table store audit table for language table';
COMMENT ON COLUMN AUDIT_LANGUAGES.LANGUAGE_ID IS 'This column store language id';
COMMENT ON COLUMN AUDIT_LANGUAGES.CREATED_DATE_TIME IS 'This column store language created table';
COMMENT ON COLUMN AUDIT_LANGUAGES.UPDATED_DATE_TIME IS 'This column store language updated table';
COMMENT ON COLUMN AUDIT_LANGUAGES.OPERATION_ID IS 'This column store operation id';

CREATE TABLE AUDIT_PART_OF_SPEECHES
(
	PART_OF_SPEECH_ID   NUMBER(10,0) NOT NULL ,
	CREATED_DATE_TIME TIMESTAMP NULL ,
	UPDATED_DATE_TIME TIMESTAMP NOT NULL ,
	OPERATION_ID NUMBER(1,0) NOT NULL,
	CONSTRAINT A_P_PART_OF_SPEECH_ID_FK FOREIGN KEY (PART_OF_SPEECH_ID) REFERENCES T_PART_OF_SPEECHES (PART_OF_SPEECH_ID),
	CONSTRAINT A_P_OPERATION_ID_FK FOREIGN KEY (OPERATION_ID) REFERENCES T_C_OPERATIONS (OPERATION_ID)
);
COMMENT ON TABLE AUDIT_PART_OF_SPEECHES IS 'This table store audit table for part of speech table';
COMMENT ON COLUMN AUDIT_PART_OF_SPEECHES.PART_OF_SPEECH_ID IS 'This column store part of speech id';
COMMENT ON COLUMN AUDIT_PART_OF_SPEECHES.CREATED_DATE_TIME IS 'This column store part of speech created table';
COMMENT ON COLUMN AUDIT_PART_OF_SPEECHES.UPDATED_DATE_TIME IS 'This column store part of speech updated table';
COMMENT ON COLUMN AUDIT_PART_OF_SPEECHES.OPERATION_ID IS 'This column store operation id';

CREATE TABLE AUDIT_WORDS
(
	WORD_ID   NUMBER(10,0) NOT NULL ,
	CREATED_DATE_TIME TIMESTAMP NULL ,
	UPDATED_DATE_TIME TIMESTAMP NOT NULL ,
	OPERATION_ID NUMBER(1,0) NOT NULL,
	CONSTRAINT A_W_WORD_ID_FK FOREIGN KEY (WORD_ID) REFERENCES T_WORDS (WORD_ID),
	CONSTRAINT A_W_OPERATION_ID_FK FOREIGN KEY (OPERATION_ID) REFERENCES T_C_OPERATIONS (OPERATION_ID)
);
COMMENT ON TABLE AUDIT_WORDS IS 'This table store audit table for word table';
COMMENT ON COLUMN AUDIT_WORDS.WORD_ID IS 'This column store word id';
COMMENT ON COLUMN AUDIT_WORDS.CREATED_DATE_TIME IS 'This column store word created table';
COMMENT ON COLUMN AUDIT_WORDS.UPDATED_DATE_TIME IS 'This column store word updated table';
COMMENT ON COLUMN AUDIT_WORDS.OPERATION_ID IS 'This column store operation id';

CREATE TABLE AUDIT_TRANSLATES
(
	TRANSLATE_ID   NUMBER(10,0) NOT NULL ,
	CREATED_DATE_TIME TIMESTAMP NULL ,
	UPDATED_DATE_TIME TIMESTAMP NOT NULL ,
	OPERATION_ID NUMBER(1,0) NOT NULL,
	CONSTRAINT A_T_TRANSLATE_ID_FK FOREIGN KEY (TRANSLATE_ID) REFERENCES T_TRANSLATES (TRANSLATE_ID),
	CONSTRAINT A_T_OPERATION_ID_FK FOREIGN KEY (OPERATION_ID) REFERENCES T_C_OPERATIONS (OPERATION_ID)
);
COMMENT ON TABLE AUDIT_TRANSLATES IS 'This table store audit table for translates table';
COMMENT ON COLUMN AUDIT_TRANSLATES.TRANSLATE_ID IS 'This column store translate id';
COMMENT ON COLUMN AUDIT_TRANSLATES.CREATED_DATE_TIME IS 'This column store translate created table';
COMMENT ON COLUMN AUDIT_TRANSLATES.UPDATED_DATE_TIME IS 'This column store translate updated table';
COMMENT ON COLUMN AUDIT_TRANSLATES.OPERATION_ID IS 'This column store operation id';
