--PROMPT---------------CREATE AUDITED TABLES--------------;
CREATE TABLE AUDIT_LANGUAGES
(
	LANGUAGE_ID   NUMBER(10,0) NOT NULL ,
	CREATED_DATE_TIME TIMESTAMP NULL ,
	UPDATED_DATE_TIME TIMESTAMP NOT NULL ,
	OPERATION_ID NUMBER(1,0) NOT NULL,
	CONSTRAINT A_L_LANGUAGE_ID_FK FOREIGN KEY (LANGUAGE_ID) REFERENCES T_LANGUAGES (LANGUAGE_ID),
	CONSTRAINT A_L_OPERATION_ID_FK FOREIGN KEY (OPERATION_ID) REFERENCES T_C_OPERATIONS (OPERATION_ID)
);

CREATE TABLE AUDIT_PART_OF_SPEECHES
(
	PART_OF_SPEECH_ID   NUMBER(10,0) NOT NULL ,
	CREATED_DATE_TIME TIMESTAMP NULL ,
	UPDATED_DATE_TIME TIMESTAMP NOT NULL ,
	OPERATION_ID NUMBER(1,0) NOT NULL,
	CONSTRAINT A_P_PART_OF_SPEECH_ID_FK FOREIGN KEY (PART_OF_SPEECH_ID) REFERENCES T_PART_OF_SPEECHES (PART_OF_SPEECH_ID),
	CONSTRAINT A_P_OPERATION_ID_FK FOREIGN KEY (OPERATION_ID) REFERENCES T_C_OPERATIONS (OPERATION_ID)
);

CREATE TABLE AUDIT_WORDS
(
	WORD_ID   NUMBER(10,0) NOT NULL ,
	CREATED_DATE_TIME TIMESTAMP NULL ,
	UPDATED_DATE_TIME TIMESTAMP NOT NULL ,
	OPERATION_ID NUMBER(1,0) NOT NULL,
	CONSTRAINT A_W_WORD_ID_FK FOREIGN KEY (WORD_ID) REFERENCES T_WORDS (WORD_ID),
	CONSTRAINT A_W_OPERATION_ID_FK FOREIGN KEY (OPERATION_ID) REFERENCES T_C_OPERATIONS (OPERATION_ID)
);

CREATE TABLE AUDIT_TRANSLATES
(
	TRANSLATE_ID   NUMBER(10,0) NOT NULL ,
	CREATED_DATE_TIME TIMESTAMP NULL ,
	UPDATED_DATE_TIME TIMESTAMP NOT NULL ,
	OPERATION_ID NUMBER(1,0) NOT NULL,
	CONSTRAINT A_T_TRANSLATE_ID_FK FOREIGN KEY (TRANSLATE_ID) REFERENCES T_TRANSLATES (TRANSLATE_ID),
	CONSTRAINT A_T_OPERATION_ID_FK FOREIGN KEY (OPERATION_ID) REFERENCES T_C_OPERATIONS (OPERATION_ID)
);
