--PROMPT---------------CREATE VIEWS--------------;
--CREATE VIEWIES
CREATE OR REPLACE VIEW V_LANGUAGES AS
	SELECT *
	FROM T_LANGUAGES;

CREATE OR REPLACE VIEW V_PART_OF_SPEECHES AS
	SELECT *
	FROM T_PART_OF_SPEECHES;

CREATE OR REPLACE VIEW V_WORDS AS
	SELECT W.*, L.LANGUAGE_NAME
	FROM T_WORDS W INNER JOIN T_LANGUAGES L ON L.LANGUAGE_ID = W.LANGUAGE_ID;

CREATE OR REPLACE VIEW V_WORDS_PART_OF_SPEECHES AS
	SELECT WPOS.*, W.WORD, W.LANGUAGE_NAME, POS.PART_OF_SPEECH
	FROM T_WORDS_PART_OF_SPEECHES WPOS INNER JOIN V_WORDS W ON WPOS.WORD_ID = W.WORD_ID
	INNER JOIN T_PART_OF_SPEECHES POS ON POS.PART_OF_SPEECH_ID = WPOS.PART_OF_SPEECH_ID;

CREATE OR REPLACE VIEW V_TRANSLATES AS
	SELECT T.TRANSLATE_ID, T.PART_OF_SPEECH_WORD_ID_F,
		FIRST_WORD.WORD_ID AS FW_WORD_ID, FIRST_WORD.PART_OF_SPEECH_ID AS FW_PART_OF_SPEECH_ID,
    FIRST_WORD.WORD AS FW_WORD, FIRST_WORD.LANGUAGE_NAME AS FW_LANGUAGE_NAME,
    FIRST_WORD.PART_OF_SPEECH AS FW_PART_OF_SPEECH,
    T.PART_OF_SPEECH_WORD_ID_S,
		SECOND_WORD.WORD_ID AS SW_WORD_ID, SECOND_WORD.PART_OF_SPEECH_ID AS SW_PART_OF_SPEECH_ID,
    SECOND_WORD.WORD AS SW_WORD, SECOND_WORD.LANGUAGE_NAME AS SW_LANGUAGE_NAME,
    SECOND_WORD.PART_OF_SPEECH AS SW_PART_OF_SPEECH
	FROM T_TRANSLATES T,
		(SELECT * FROM V_WORDS_PART_OF_SPEECHES VWPOS) FIRST_WORD,
		(SELECT * FROM V_WORDS_PART_OF_SPEECHES VWPOS) SECOND_WORD
	WHERE FIRST_WORD.PART_OF_SPEECH_WORD_ID = T.PART_OF_SPEECH_WORD_ID_F AND SECOND_WORD.PART_OF_SPEECH_WORD_ID = T.PART_OF_SPEECH_WORD_ID_S;

CREATE OR REPLACE VIEW V_S_TRANSLATES AS
  SELECT T.TRANSLATE_ID, T.FW_WORD, T.SW_WORD
  FROM V_TRANSLATES T;

--PROMPT---------------CREATE AUDITED VIEWS--------------;
CREATE OR REPLACE VIEW V_AUDIT_LANGUAGES AS
	SELECT l.LANGUAGE_NAME, al.*
	FROM T_LANGUAGES l INNER JOIN AUDIT_LANGUAGES al ON l.LANGUAGE_ID = al.LANGUAGE_ID;

CREATE OR REPLACE VIEW V_AUDIT_PART_OF_SPEECHES AS
	SELECT pos.PART_OF_SPEECH, apos.*
	FROM T_PART_OF_SPEECHES pos INNER JOIN AUDIT_PART_OF_SPEECHES apos ON pos.PART_OF_SPEECH_ID = apos.PART_OF_SPEECH_ID ;

CREATE OR REPLACE VIEW V_AUDIT_WORDS AS
	SELECT W.WORD, AW.*
	FROM T_WORDS W INNER JOIN AUDIT_WORDS AW ON W.WORD_ID = AW.WORD_ID;
/*
/
SHOW ERRORS;*/
