BEGIN
  FOR CUR_OBJECT IN (SELECT OBJECT_NAME, OBJECT_TYPE
  FROM USER_OBJECTS
  where OBJECT_TYPE not in('INDEX', 'PACKAGE', 'PACKAGE BODY', 'TABLE', 'SEQUENCE'))
  LOOP
    IF CUR_OBJECT.OBJECT_TYPE = 'PROGRAM' THEN
      DBMS_SCHEDULER.DROP_PROGRAM(CUR_OBJECT.OBJECT_NAME);
    ELSIF CUR_OBJECT.OBJECT_TYPE = 'SCHEDULE' THEN
      DBMS_SCHEDULER.DROP_SCHEDULE(CUR_OBJECT.OBJECT_NAME);
    ELSIF CUR_OBJECT.OBJECT_TYPE = 'JOB' THEN
      DBMS_SCHEDULER.DROP_JOB(CUR_OBJECT.OBJECT_NAME);
    END IF;
    DBMS_OUTPUT.PUT_LINE(CUR_OBJECT.OBJECT_NAME);
  END LOOP;
END;