DECLARE
  CA_ST T_STATUS_TYPES.STATUS_TYPE%TYPE := 'CREATE_ACCOUNT_BUT_NOT_ACTIVE';
  CASAC_ST T_STATUS_TYPES.STATUS_TYPE%TYPE := 'CREATE_ACCOUNT_SENT_ACTIVATION_CODE';
  CAA_ST T_STATUS_TYPES.STATUS_TYPE%TYPE := 'CREATE_ACCOUNT_ACTIVE';
BEGIN
  PKG_STATUS_TYPE.INSERT_STATUS_TYPE(CA_ST);
  PKG_STATUS_TYPE.INSERT_STATUS_TYPE(CASAC_ST);
  PKG_STATUS_TYPE.INSERT_STATUS_TYPE(CAA_ST);

  PKG_STATUS_TYPE.INSERT_NEXT_STATUS_TYPE(CA_ST, PKG_STATUS_TYPE.GET_STATUS_TYPE_ID_BY_NAME(CASAC_ST));
  PKG_STATUS_TYPE.INSERT_NEXT_STATUS_TYPE(CASAC_ST, PKG_STATUS_TYPE.GET_STATUS_TYPE_ID_BY_NAME(CAA_ST));
END;