CREATE TABLE T_STATUS_TYPES(
  STATUS_TYPE_ID RAW(32) DEFAULT sys_guid() NOT NULL,
  STATUS_TYPE VARCHAR2(100) NOT NULL,
  NEXT_STATUS_TYPE_ID RAW(32) NULL,
  CONSTRAINT STATUS_TYPE_ID_PK PRIMARY KEY (STATUS_TYPE_ID)
);
COMMENT ON TABLE T_STATUS_TYPES IS 'This table store status types';
COMMENT ON COLUMN T_STATUS_TYPES.STATUS_TYPE_ID IS 'This column store status type id';
COMMENT ON COLUMN T_STATUS_TYPES.STATUS_TYPE IS 'This column store status type';
COMMENT ON COLUMN T_STATUS_TYPES.NEXT_STATUS_TYPE_ID IS 'This column store next status type id';

CREATE TABLE T_ACCOUNT_STATUS_TYPES(
  STATUS_TYPE_ID RAW(32) NOT NULL,
  USER_ID NUMBER(10,0) NOT NULL,
  ACTION_TIMESTAMP TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
  CONSTRAINT AST_STATUS_TYPE_ID_FK FOREIGN KEY (STATUS_TYPE_ID) REFERENCES T_STATUS_TYPES(STATUS_TYPE_ID),
  CONSTRAINT AST_USER_ID_FK FOREIGN KEY (USER_ID) REFERENCES T_USERS(USER_ID)
);
COMMENT ON TABLE T_ACCOUNT_STATUS_TYPES IS 'This table store user status types';
COMMENT ON COLUMN T_ACCOUNT_STATUS_TYPES.STATUS_TYPE_ID IS 'This column store status type id';
COMMENT ON COLUMN T_ACCOUNT_STATUS_TYPES.USER_ID IS 'This column store user id';
COMMENT ON COLUMN T_ACCOUNT_STATUS_TYPES.ACTION_TIMESTAMP IS 'This column store action timestamp';