
PROMPT---DROP ROLE ROLE_COMMON_DB;
--DROP ROLE
DROP ROLE ROLE_COMMON_DB;

PROMPT ----------------DROP USER USER_WORD_DB;
--DROP USER
DROP USER USER_WORD_DB CASCADE;
DROP USER USER_USER_DB CASCADE;
DROP USER USER_COMMON_DB CASCADE;

PROMPT -----------------DROP PROFILE PR_USER_WORD_DB;
--DROP PROFILE
DROP PROFILE PR_USER_WORD_DB;


/*
PROMPT DROP TABLESPACE TEMP_TBL_USER_WORD_DB;
DROP TABLESPACE TEMP_TBL_USER_WORD_DB;
--DROP TABLESPACE
DROP TABLESPACE TEMP_TBL_USER_WORD_DB
INCLUDING CONTENTS CASCADE CONSTRAINTS;

PROMPT DROP TABLESPACE TBL_USER_WORD_DB;
DROP TABLESPACE TBL_USER_WORD_DB
INCLUDING CONTENTS CASCADE CONSTRAINTS;
*/
SHOW ERRORS;
