DECLARE
	LANGUAGE_ENG T_LANGUAGES%ROWTYPE;
	LANGUAGE_RUS T_LANGUAGES%ROWTYPE;

	T_PART_OF_SPEECHES_NOUN T_PART_OF_SPEECHES%ROWTYPE;
	T_PART_OF_SPEECHES_PRONOUN T_PART_OF_SPEECHES%ROWTYPE;
	T_PART_OF_SPEECHES_ADJECTIVE T_PART_OF_SPEECHES%ROWTYPE;
	T_PART_OF_SPEECHES_VERB T_PART_OF_SPEECHES%ROWTYPE;
	T_PART_OF_SPEECHES_ADVERB T_PART_OF_SPEECHES%ROWTYPE;
	T_PART_OF_SPEECHES_PREPOSITION T_PART_OF_SPEECHES%ROWTYPE;
	T_PART_OF_SPEECHES_CONJUCTION T_PART_OF_SPEECHES%ROWTYPE;
	T_PART_OF_SPEECHES_INTERJECT T_PART_OF_SPEECHES%ROWTYPE;
	T_PART_OF_SPEECHES_ARTICLE T_PART_OF_SPEECHES%ROWTYPE;

	T_PART_OF_SPEECHES_NOUN_RUS T_PART_OF_SPEECHES%ROWTYPE;
	T_PART_OF_SPEECHES_PRONOUN_RUS T_PART_OF_SPEECHES%ROWTYPE;
	T_PART_OF_SPEECHES_ADJECT_RUS T_PART_OF_SPEECHES%ROWTYPE;
	T_PART_OF_SPEECHES_VERB_RUS T_PART_OF_SPEECHES%ROWTYPE;
	T_PART_OF_SPEECHES_ADVERB_RUS T_PART_OF_SPEECHES%ROWTYPE;
	T_PART_OF_SPEECHES_PREPOS_RUS T_PART_OF_SPEECHES%ROWTYPE;
	T_PART_OF_SPEECHES_CONJUCT_RUS T_PART_OF_SPEECHES%ROWTYPE;
	T_PART_OF_SPEECHES_INTERJ_RUS T_PART_OF_SPEECHES%ROWTYPE;
	T_PART_OF_SPEECHES_ARTICLE_RUS T_PART_OF_SPEECHES%ROWTYPE;

	T_WORDS_REPLAY_EN T_WORDS%ROWTYPE;
	T_WORDS_PEREIGROVKA_RU T_WORDS%ROWTYPE;
	T_WORDS_PEREIGROVATI_RU T_WORDS%ROWTYPE;

	T_W_P_OF_S_REPLAY T_WORDS_PART_OF_SPEECHES%ROWTYPE;
	T_W_P_OF_S_PEREIGROVKA T_WORDS_PART_OF_SPEECHES%ROWTYPE;
	T_W_P_OF_S_PEREIGROVATI T_WORDS_PART_OF_SPEECHES%ROWTYPE;
	
	T_TRANSLATES_REPLAY_NOUN T_TRANSLATES%ROWTYPE;
	T_TRANSLATES_REPLAY_VERB T_TRANSLATES%ROWTYPE;
BEGIN
	--clean up
	PACKAGE_WORDS_W_PART_OF_SPE.DELETE_ALL_W_PART_OF_SPEECHES;
	dbms_output.put_line('delete all WORDS_PART_OF_SPEECHES!');
	PACKAGE_WORDS_WORDS.DELETE_ALL_WORD;
	dbms_output.put_line('delete all WORDS!');
	PACKAGE_WORDS_LANGUAGES.DELETE_ALL_LANGUAGE(DELETE_AUDIT_TABLE_IN => 1);
	dbms_output.put_line('delete all LANGUAGES!');
	PACKAGE_WORDS_PART_OF_SPEECHES.DELETE_ALL_PART_OF_SPEECH(DELETE_AUDIT_TABLE_IN => 1);
	dbms_output.put_line('delete all PART_OF_SPEECHES!');

	--PACKAGE_WORDS_LANGUAGES
	LANGUAGE_ENG.LANGUAGE_NAME := 'ENG';
	LANGUAGE_RUS.LANGUAGE_NAME := 'RUS';

	PACKAGE_WORDS_LANGUAGES.INSERT_LANGUAGE(LANGUAGE_NAME_IN => LANGUAGE_ENG.LANGUAGE_NAME);
	dbms_output.put_line('INSERTED ENG LANGUAGE!');
	PACKAGE_WORDS_LANGUAGES.INSERT_LANGUAGE(LANGUAGE_NAME_IN => LANGUAGE_RUS.LANGUAGE_NAME);
	dbms_output.put_line('INSERTED RUS LANGUAGE!');

	PACKAGE_WORDS_LANGUAGES.SELECT_LANGUAGE_BY_NAME(LANGUAGE_ENG.LANGUAGE_NAME, LANGUAGE_ENG.LANGUAGE_ID);
	PACKAGE_WORDS_LANGUAGES.SELECT_LANGUAGE_BY_NAME(LANGUAGE_RUS.LANGUAGE_NAME, LANGUAGE_RUS.LANGUAGE_ID);

	T_PART_OF_SPEECHES_NOUN.PART_OF_SPEECH := 'noun';
	T_PART_OF_SPEECHES_PRONOUN.PART_OF_SPEECH := 'pronoun';
	T_PART_OF_SPEECHES_ADJECTIVE.PART_OF_SPEECH := 'adjective';
	T_PART_OF_SPEECHES_VERB.PART_OF_SPEECH := 'verb';
	T_PART_OF_SPEECHES_ADVERB.PART_OF_SPEECH := 'adverb';
	T_PART_OF_SPEECHES_PREPOSITION.PART_OF_SPEECH := 'preposition';
	T_PART_OF_SPEECHES_CONJUCTION.PART_OF_SPEECH := 'conjunction';
	T_PART_OF_SPEECHES_INTERJECT.PART_OF_SPEECH := 'interjection';
	T_PART_OF_SPEECHES_ARTICLE.PART_OF_SPEECH := 'article';

	--PACKAGE_WORDS_PART_OF_SPEECHES
	PACKAGE_WORDS_PART_OF_SPEECHES.INSERT_PART_OF_SPEECH(T_PART_OF_SPEECHES_NOUN.PART_OF_SPEECH);
	PACKAGE_WORDS_PART_OF_SPEECHES.SELECT_PART_OF_SPEECH_BY_NAME(T_PART_OF_SPEECHES_NOUN.PART_OF_SPEECH,
																T_PART_OF_SPEECHES_NOUN.PART_OF_SPEECH_ID);
	PACKAGE_WORDS_PART_OF_SPEECHES.INSERT_PART_OF_SPEECH(T_PART_OF_SPEECHES_PRONOUN.PART_OF_SPEECH);
	PACKAGE_WORDS_PART_OF_SPEECHES.INSERT_PART_OF_SPEECH(T_PART_OF_SPEECHES_ADJECTIVE.PART_OF_SPEECH);
	PACKAGE_WORDS_PART_OF_SPEECHES.INSERT_PART_OF_SPEECH(T_PART_OF_SPEECHES_VERB.PART_OF_SPEECH);
	PACKAGE_WORDS_PART_OF_SPEECHES.SELECT_PART_OF_SPEECH_BY_NAME(T_PART_OF_SPEECHES_VERB.PART_OF_SPEECH,
																T_PART_OF_SPEECHES_VERB.PART_OF_SPEECH_ID);
	PACKAGE_WORDS_PART_OF_SPEECHES.INSERT_PART_OF_SPEECH(T_PART_OF_SPEECHES_ADVERB.PART_OF_SPEECH);
	PACKAGE_WORDS_PART_OF_SPEECHES.INSERT_PART_OF_SPEECH(T_PART_OF_SPEECHES_PREPOSITION.PART_OF_SPEECH);
	PACKAGE_WORDS_PART_OF_SPEECHES.INSERT_PART_OF_SPEECH(T_PART_OF_SPEECHES_CONJUCTION.PART_OF_SPEECH);
	PACKAGE_WORDS_PART_OF_SPEECHES.INSERT_PART_OF_SPEECH(T_PART_OF_SPEECHES_INTERJECT.PART_OF_SPEECH);
	PACKAGE_WORDS_PART_OF_SPEECHES.INSERT_PART_OF_SPEECH(T_PART_OF_SPEECHES_ARTICLE.PART_OF_SPEECH);
	dbms_output.put_line('INSERTED ALL PART_OF_SPEECHES!');

	T_PART_OF_SPEECHES_NOUN_RUS.PART_OF_SPEECH := 'существительное';
	T_PART_OF_SPEECHES_PRONOUN_RUS.PART_OF_SPEECH := 'местоимение';
	T_PART_OF_SPEECHES_ADJECT_RUS.PART_OF_SPEECH := 'прилагательное';
	T_PART_OF_SPEECHES_VERB_RUS.PART_OF_SPEECH := 'глагол';
	T_PART_OF_SPEECHES_ADVERB_RUS.PART_OF_SPEECH := 'наречие';
	T_PART_OF_SPEECHES_PREPOS_RUS.PART_OF_SPEECH := 'предлог';
	T_PART_OF_SPEECHES_CONJUCT_RUS.PART_OF_SPEECH := 'конъюнкция';
	T_PART_OF_SPEECHES_INTERJ_RUS.PART_OF_SPEECH := 'междометие';
	T_PART_OF_SPEECHES_ARTICLE_RUS.PART_OF_SPEECH := 'артикль';

	--PACKAGE_WORDS_WORDS
	--ENG
	PACKAGE_WORDS_WORDS.INSERT_WORD(T_PART_OF_SPEECHES_NOUN.PART_OF_SPEECH, LANGUAGE_ENG.LANGUAGE_ID);
	PACKAGE_WORDS_WORDS.INSERT_WORD(T_PART_OF_SPEECHES_PRONOUN.PART_OF_SPEECH, LANGUAGE_ENG.LANGUAGE_ID);
	PACKAGE_WORDS_WORDS.INSERT_WORD(T_PART_OF_SPEECHES_ADJECTIVE.PART_OF_SPEECH, LANGUAGE_ENG.LANGUAGE_ID);
	PACKAGE_WORDS_WORDS.INSERT_WORD(T_PART_OF_SPEECHES_VERB.PART_OF_SPEECH, LANGUAGE_ENG.LANGUAGE_ID);
	PACKAGE_WORDS_WORDS.INSERT_WORD(T_PART_OF_SPEECHES_ADVERB.PART_OF_SPEECH, LANGUAGE_ENG.LANGUAGE_ID);
	PACKAGE_WORDS_WORDS.INSERT_WORD(T_PART_OF_SPEECHES_PREPOSITION.PART_OF_SPEECH, LANGUAGE_ENG.LANGUAGE_ID);
	PACKAGE_WORDS_WORDS.INSERT_WORD(T_PART_OF_SPEECHES_CONJUCTION.PART_OF_SPEECH, LANGUAGE_ENG.LANGUAGE_ID);
	PACKAGE_WORDS_WORDS.INSERT_WORD(T_PART_OF_SPEECHES_INTERJECT.PART_OF_SPEECH, LANGUAGE_ENG.LANGUAGE_ID);
	PACKAGE_WORDS_WORDS.INSERT_WORD(T_PART_OF_SPEECHES_ARTICLE.PART_OF_SPEECH, LANGUAGE_ENG.LANGUAGE_ID);

	--RUS
	PACKAGE_WORDS_WORDS.INSERT_WORD(T_PART_OF_SPEECHES_NOUN_RUS.PART_OF_SPEECH, LANGUAGE_RUS.LANGUAGE_ID);
	PACKAGE_WORDS_WORDS.INSERT_WORD(T_PART_OF_SPEECHES_PRONOUN_RUS.PART_OF_SPEECH, LANGUAGE_RUS.LANGUAGE_ID);
	PACKAGE_WORDS_WORDS.INSERT_WORD(T_PART_OF_SPEECHES_ADJECT_RUS.PART_OF_SPEECH, LANGUAGE_RUS.LANGUAGE_ID);
	PACKAGE_WORDS_WORDS.INSERT_WORD(T_PART_OF_SPEECHES_VERB_RUS.PART_OF_SPEECH, LANGUAGE_RUS.LANGUAGE_ID);
	PACKAGE_WORDS_WORDS.INSERT_WORD(T_PART_OF_SPEECHES_ADVERB_RUS.PART_OF_SPEECH, LANGUAGE_RUS.LANGUAGE_ID);
	PACKAGE_WORDS_WORDS.INSERT_WORD(T_PART_OF_SPEECHES_PREPOS_RUS.PART_OF_SPEECH, LANGUAGE_RUS.LANGUAGE_ID);
	PACKAGE_WORDS_WORDS.INSERT_WORD(T_PART_OF_SPEECHES_CONJUCT_RUS.PART_OF_SPEECH, LANGUAGE_RUS.LANGUAGE_ID);
	PACKAGE_WORDS_WORDS.INSERT_WORD(T_PART_OF_SPEECHES_INTERJ_RUS.PART_OF_SPEECH, LANGUAGE_RUS.LANGUAGE_ID);
	PACKAGE_WORDS_WORDS.INSERT_WORD(T_PART_OF_SPEECHES_ARTICLE_RUS.PART_OF_SPEECH, LANGUAGE_RUS.LANGUAGE_ID);

	T_WORDS_REPLAY_EN.WORD := 'replay';
	T_WORDS_REPLAY_EN.LANGUAGE_ID := LANGUAGE_ENG.LANGUAGE_ID;

	T_WORDS_PEREIGROVKA_RU.WORD := 'переигровка';
	T_WORDS_PEREIGROVKA_RU.LANGUAGE_ID := LANGUAGE_RUS.LANGUAGE_ID;

	T_WORDS_PEREIGROVATI_RU.WORD := 'переигрывать';
	T_WORDS_PEREIGROVATI_RU.LANGUAGE_ID := LANGUAGE_RUS.LANGUAGE_ID;

	PACKAGE_WORDS_WORDS.INSERT_WORD(T_WORDS_REPLAY_EN);
	PACKAGE_WORDS_WORDS.INSERT_WORD(T_WORDS_PEREIGROVKA_RU);
	PACKAGE_WORDS_WORDS.INSERT_WORD(T_WORDS_PEREIGROVATI_RU);
	dbms_output.put_line('INSERTED ALL WORDS!');

	T_W_P_OF_S_REPLAY.WORD_ID := PACKAGE_WORDS_WORDS.GET_SELECT_WORD_BY_WORD(T_WORDS_REPLAY_EN.WORD);
	T_W_P_OF_S_REPLAY.PART_OF_SPEECH_ID := T_PART_OF_SPEECHES_VERB.PART_OF_SPEECH_ID;
	PACKAGE_WORDS_W_PART_OF_SPE.INSERT_WORDS_PART_OF_SPEECHES(T_W_P_OF_S_REPLAY);
	T_W_P_OF_S_REPLAY.PART_OF_SPEECH_WORD_ID := PACKAGE_WORDS_W_PART_OF_SPE.SELECT_WORDS_PART_OF_SPEECHES(T_W_P_OF_S_REPLAY.WORD_ID, T_W_P_OF_S_REPLAY.PART_OF_SPEECH_ID);
	--dbms_output.put_line('GET!T_W_P_OF_S_REPLAY-' || T_W_P_OF_S_REPLAY.PART_OF_SPEECH_WORD_ID || '_____' || T_W_P_OF_S_REPLAY.PART_OF_SPEECH_ID);

	T_W_P_OF_S_PEREIGROVKA.WORD_ID := PACKAGE_WORDS_WORDS.GET_SELECT_WORD_BY_WORD(T_WORDS_PEREIGROVKA_RU.WORD);
	T_W_P_OF_S_PEREIGROVKA.PART_OF_SPEECH_ID := T_PART_OF_SPEECHES_NOUN.PART_OF_SPEECH_ID;
	PACKAGE_WORDS_W_PART_OF_SPE.INSERT_WORDS_PART_OF_SPEECHES(T_W_P_OF_S_PEREIGROVKA);
	T_W_P_OF_S_PEREIGROVKA.PART_OF_SPEECH_WORD_ID := PACKAGE_WORDS_W_PART_OF_SPE.SELECT_WORDS_PART_OF_SPEECHES(T_W_P_OF_S_PEREIGROVKA.WORD_ID, T_W_P_OF_S_PEREIGROVKA.PART_OF_SPEECH_ID);

	T_W_P_OF_S_PEREIGROVATI.WORD_ID := PACKAGE_WORDS_WORDS.GET_SELECT_WORD_BY_WORD(T_WORDS_PEREIGROVATI_RU.WORD);
	T_W_P_OF_S_PEREIGROVATI.PART_OF_SPEECH_ID := T_PART_OF_SPEECHES_VERB.PART_OF_SPEECH_ID;
	PACKAGE_WORDS_W_PART_OF_SPE.INSERT_WORDS_PART_OF_SPEECHES(T_W_P_OF_S_PEREIGROVATI);
	T_W_P_OF_S_PEREIGROVATI.PART_OF_SPEECH_WORD_ID := PACKAGE_WORDS_W_PART_OF_SPE.SELECT_WORDS_PART_OF_SPEECHES(T_W_P_OF_S_PEREIGROVATI.WORD_ID, T_W_P_OF_S_PEREIGROVATI.PART_OF_SPEECH_ID);	
	dbms_output.put_line('INSERTED ALL T_WORDS_PART_OF_SPEECHES!');
	
	T_TRANSLATES_REPLAY_NOUN := PACKAGE_CONVERTER.WORDS_PART_OF_SPEECHES_TO_TRAN(T_W_P_OF_S_REPLAY, T_W_P_OF_S_PEREIGROVKA);
	PACKAGE_WORDS_T_TRANSLATES.INSERT_TRANSLATES(T_TRANSLATES_REPLAY_NOUN);
	
	T_TRANSLATES_REPLAY_VERB := PACKAGE_CONVERTER.WORDS_PART_OF_SPEECHES_TO_TRAN(T_W_P_OF_S_REPLAY, T_W_P_OF_S_PEREIGROVATI);
	PACKAGE_WORDS_T_TRANSLATES.INSERT_TRANSLATES(T_TRANSLATES_REPLAY_VERB);
	dbms_output.put_line('INSERTED ALL T_TRANSLATES!');
  
  
END;